### PR TITLE
DT-1116: ✨ Stab at rename script

### PR DESCRIPTION
**Pull request by petergphillips**

### CODE REVIEW

**Comment by mikehalmamoj** [comment]
It doesn't rename the source files HmppsTemplateKotlin.kt / HmppsTemlpateKotlinExceptionHandler.kt - my bad I forgot to add that to the instructions.

**Comment by mikehalmamoj** [comment]
Chart.yaml still has name hmpps-template-kotlin

**Review by mikehalmamoj — CHANGES_REQUESTED** [review]
Yeah, really good - just that source file rename outstanding.

**Comment by mikehalmamoj** [comment]
> Yeah, really good - just that source file rename outstanding.

**Review by mikehalmamoj — APPROVED** [review]

**Review by mattops — APPROVED** [review]
LGMT

**Pull request merged**
